// apps/www/src/components/elements/Link.svelte
<script lang="ts">
  export let name = "";
  export let to: `http${"s" | ""}://${string}`;
  export let size: "sm" | "lg" = "lg";
</script>

<a
  class={size == "lg" ? "p-3" : "p-2"}
  href={to}
  target="_blank"
  rel="noopener"
  {...$$restProps}
>
  <slot />

  {#if name}
    <p class={size == "lg" ? "font-bold text-2xl" : "text-lg"}>{name}</p>
  {/if}
</a>

<style lang="postcss">
  a {
    @apply border-2 border-slate-400 bg-slate-800 hover:bg-slate-700;
    @apply transition-all rounded-lg flex flex-row items-center gap-2 cursor-pointer select-none;
  }
</style>

// apps/www/components/Link.tsx
import clsx from "clsx";
import type { FC, PropsWithChildren } from "react";

interface LinkProps extends PropsWithChildren {
  name: string;
  to: `http${"s" | ""}://${string}.${string}`;
  size?: "sm" | "lg";
}

const Link: FC<LinkProps> = ({
  name,
  to,
  size = "lg",
  children,
}: LinkProps) => {
  return (
    <a
      href={to}
      target="_blank"
      rel="noreferrer"
      className={clsx(
        "flex cursor-pointer select-none flex-row items-center gap-2 rounded-lg border-2 border-slate-400 bg-slate-800 transition-all hover:bg-slate-700",
        size == "lg" ? "p-3" : "p-2"
      )}
    >
      {children}

      {name && (
        <p className={size == "lg" ? "text-2xl font-bold" : "text-lg"}>
          {name}
        </p>
      )}
    </a>
  );
};

export default Link;
