// apps/www/src/components/layouts/Footer.svelte
<script lang="ts">
  import Github from "svelte-bootstrap-icons/lib/Github.svelte";
</script>

<footer class="mt-8 self-center">
  <div class="flex flex-col items-center gap-2 sm:flex-row">
    <p>Source Code of this website is available on</p>
    <a
      href="https://github.com/Leomotors/Leomotors"
      target="_blank"
      rel="noreferrer"
      class="flex items-center gap-1 text-slate-300 transition-colors hover:text-slate-400"
    >
      <Github width="20" height="20" />
      <p>GitHub</p>
    </a>
  </div>
</footer>

// apps/www/components/layouts/Footer.tsx
import type { FC } from "react";
import { Github } from "react-bootstrap-icons";

const Footer: FC = () => {
  return (
    <footer className="mt-8 self-center">
      <div className="flex flex-col items-center gap-2 sm:flex-row">
        <p>Source Code of this website is available on</p>
        <a
          href="https://github.com/Leomotors/Leomotors"
          target="_blank"
          rel="noreferrer"
          className="flex items-center gap-1 text-slate-300 transition-colors hover:text-slate-400"
        >
          <Github size="20" />
          <p>GitHub</p>
        </a>
      </div>
    </footer>
  );
};

export default Footer;
